### ISSUE TITLE
fix formatting of the TrapDate field for use in the assignNode function

### ISSUE THREAD

**Issue by ryankinzer** [KevinSee/PITcleanr_old#12]
The problem could be fixed by formatting the date immediately when the LGR trapping database is queried.

**Comment by ryankinzer** [comment]
Collection date comes in as a character string when using readr::read_csv and a factor with base::read.csv, Either way, the "if(class(date))" portion only re-formats the date if the file is read as a date, which neither read_csv or read.csv does.

**Comment by KevinSee** [comment]
One of Ryan's latest pull requests dealt with this issue. Thanks!
